### ISSUE TITLE
Lazy SOCP constraints

### ISSUE THREAD

**Issue by kaarthiksundar** [mlubin/JuMPChance.jl#10]
I am trying to add a Lazy constraint of the form x*x <= yz using

```
@addLazyConstraint(cb, varterm[sc,l,t,k]*varterm[sc,l,t,k] <= yterm[sc,l,t,k]*slack[sc,l,t])
```

Apparently, the syntax is not implemented in JuMPChance or JuMP. (Reposting the issue in JuMP).

The error it throws is as follows

```
ERROR: `addLazyConstraint` has no method matching addLazyConstraint(::CplexLazyCallbackData, ::GenericQuadConstraint{GenericQuadExpr{Float64,Variable}})
```

**Comment by mlubin** [comment]
Ref https://github.com/JuliaOpt/JuMP.jl/issues/495
