### ISSUE TITLE
Run time error for JuMP Chance

### ISSUE THREAD

**Issue by kaarthiksundar** [mlubin/JuMPChance.jl#2]
```
Iteration 0: 4 constraint violations, 0 objective linearization violations
ERROR: Tried to set LB != -Inf on a LEQ constraint (index 908)
 in error at error.jl:21
 in set_constrLB! at /home/kaarthik/.julia/v0.3/CPLEX/src/cpx_constrs.jl:250
 in setconstrLB! at /home/kaarthik/.julia/v0.3/CPLEX/src/CplexSolverInterface.jl:75
 in solveLP at /home/kaarthik/.julia/v0.3/JuMP/src/solvers.jl:210
 in solve at /home/kaarthik/.julia/v0.3/JuMP/src/solvers.jl:34
 in solvecc_cuts at /home/kaarthik/.julia/v0.3/JuMPChance/src/solve.jl:266
 in solvehook at /home/kaarthik/.julia/v0.3/JuMPChance/src/solve.jl:113
 in solve at /home/kaarthik/.julia/v0.3/JuMP/src/solvers.jl:8
 in createmodel at /home/kaarthik/Dropbox/SharedFolders/Kaarthik_Harsha/LANL/SCCOPF-    case96/codejl/model.jl:116
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
while loading /home/kaarthik/Dropbox/SharedFolders/Kaarthik_Harsha/LANL/SCCOPF-case96/codejl/ccopfmodel_simulation.jl, in expression starting on line 78
```

What does this error say?

**Comment by mlubin** [comment]
Something's quite weird with the cuts which are being generated. Does the model solve with `method=:Reformulate`?

**Comment by kaarthiksundar** [comment]
In fact, there is some thing more weird that is happening. I add all the chance constraints to the model and solve the model. Later, I check based on the solution I obtain, if the SOCP constraints are satisfied and apparently, it is not for a certain cases. I am now double checking to see if I have some mistake in my code. With regards to the error above, it was a one time thing. When I ran it again, it ran alright. I don't see how that should happen.

**Comment by kaarthiksundar** [comment]
I was able to replicate the error. And yes, what you suggested works. The reformulation is able to solve the problem where as the Cuts throws the error. But even after solving the problem by reformulation, there seems to be quite a number of constraint violations.

**Comment by mlubin** [comment]
For checking feasibility post solve, you can use the `satisfied_with_probability` function which isn't documented yet:
https://github.com/mlubin/JuMPChance.jl/blob/3121399f6bda6d7e30752e1446729ffce6081833/test/runtests.jl#L555

**Comment by kaarthiksundar** [comment]
What is the syntax and how to use it?

**Comment by mlubin** [comment]
As in the example there, `@addConstraint` returns a reference object which you pass to this function.

**Comment by mlubin** [comment]
Oh, doesn't seem to be implemented yet for simple chance constraints. Won't be hard to do though.

**Comment by kaarthiksundar** [comment]
```
satisfied_with_probability` has no method matching satisfied_with_probability(::ConstraintRef{ChanceConstr})
```

**Comment by mlubin** [comment]
Yes, I need to slightly tweak the code here: https://github.com/mlubin/JuMPChance.jl/blob/0b1b9cb5471b55cccb3f42e4a1e0047bbfdb5d73/src/JuMPChance.jl#L209

**Comment by mlubin** [comment]
(PRs accepted)

**Comment by kaarthiksundar** [comment]
Okay, I did check the code from my side. It seems to be correct. And it does give violations for the chance constraints. Also, for now, reformulate option works fine for the SOC program. But, I intend to add binary variables into the formulation; in this case the cut option might work better.

**Comment by mlubin** [comment]
Commit https://github.com/mlubin/JuMPChance.jl/commit/8d3bb7f01a5f844f7791444f674bbc272067a78c has an implementation of `satisfied_with_probability` that should work.

**Comment by mlubin** [comment]
How large are the violations of the chance constraints?

**Comment by kaarthiksundar** [comment]
I replaced the JuMPChance.jl from GitHub. I get the following error

```
ERROR: getVar not defined
 in addcuts at /home/kaarthik/.julia/v0.3/JuMPChance/src/solve.jl:181
 in solvecc_cuts at /home/kaarthik/.julia/v0.3/JuMPChance/src/solve.jl:257
 in solvehook at /home/kaarthik/.julia/v0.3/JuMPChance/src/solve.jl:113
 in solve at /home/kaarthik/.julia/v0.3/JuMP/src/solvers.jl:8
 in createmodel at /home/kaarthik/Dropbox/SharedFolders/Kaarthik_Harsha/LANL/SCCOPF-    case96/codejl/model.jl:111
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
while loading /home/kaarthik/Dropbox/SharedFolders/Kaarthik_Harsha/LANL/SCCOPF-case96/codejl/ccopfmodel_simulation.jl, in expression starting on line 79
```

**Comment by kaarthiksundar** [comment]
I ve changed getVar to getVariance

**Comment by kaarthiksundar** [comment]
The violations are in the range (0,9). Actually, only a very few violations are greater than 5.

**Comment by mlubin** [comment]
You could try decreasing the feasibility tolerances in CPLEX. Also try a
more numerically stable solver like Mosek (free academic licenses).

**Comment by kaarthiksundar** [comment]
Installed Mosek, tried with same result.

**Comment by mlubin** [comment]
Guessing we can close this
