### ISSUE TITLE
LazyCallBack getValue error

### ISSUE THREAD

**Issue by kaarthiksundar** [mlubin/JuMPChance.jl#3]
I am trying to use implement a LazyCallback for a mixed integer program using a chance model and when I use getValue(x), JuMP throws an error saying x is not defined. I checked the original model and x is defined. 

What could be the cause of this issue? Is it because JuMP chance already invokes the LazyCallback once and I cannot invoke it again?

**Comment by mlubin** [comment]
Is this resolved? We follow Julia's scoping rules, so the variable `x` needs to be within the scope of the callback function for you to be able to access its value.

**Comment by kaarthiksundar** [comment]
Resolved.
