### ISSUE TITLE
JuMPChance adding LazyConstraints

### ISSUE THREAD

**Issue by kaarthiksundar** [mlubin/JuMPChance.jl#8]
JuMPChance throws an error if I do in a LazyCallback

```
@addLazyConstraint(cb, socp[k=1:numfarms], varterm[k]*varterm[k] <= yterm[k]*t)
```

It actually says wrong number of arguments. I assume that this syntax is not implemented as a part of JuMP and hence JuMPChance. Is this the reason or is it something else.

**Comment by mlubin** [comment]
Yes, this syntax isn't implemented, just write `@addLazyConstraint` in a loop.
