### ISSUE TITLE
JuMPChance additional LazyCallback

### ISSUE THREAD

**Issue by kaarthiksundar** [mlubin/JuMPChance.jl#9]
JuMPChance does not seem to allow adding additional Lazycallback functions. When doing so, the following error popped up

```
 ERROR: Expected cb to be a JuMP model but it has type CplexLazyCallbackData
```

How easy or difficult is it to add this option into JuMPChance?

**Comment by mlubin** [comment]
You would get this message if you try to use `cb` in something like `@defVar` or `@addConstraint`. Make sure you use `@addLazyConstraint`.

**Comment by kaarthiksundar** [comment]
Can't I use defvar inside the callback. I am not using addconstraint. If not is there a way to get around this. 

—

**Comment by mlubin** [comment]
No, you can't use `@defVar` inside the callback. There's no solver hooked up which supports this.

**Comment by kaarthiksundar** [comment]
Okay, does that mean JuMP also does not support this?

**Comment by mlubin** [comment]
Well yes, there's no syntax to add variables inside of callbacks, and we won't add one until there's a solver which supports it.

**Comment by mlubin** [comment]
Ref https://github.com/JuliaOpt/JuMP.jl/issues/496 for an improved error message
